# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: portfolio.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'portfolio.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import regime_pb2 as regime__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fportfolio.proto\x12\x05quant\x1a\x0cregime.proto\"\x8d\x01\n\x10SnapshotResponse\x12\x13\n\x0btotal_value\x18\x01 \x01(\x01\x12\x14\n\x0c\x64\x61ily_return\x18\x02 \x01(\x01\x12\x14\n\x0csharpe_ratio\x18\x03 \x01(\x01\x12\x14\n\x0cmax_drawdown\x18\x04 \x01(\x01\x12\x0e\n\x06regime\x18\x05 \x01(\t\x12\x12\n\nkill_level\x18\x06 \x01(\t\"G\n\x0ePipelineStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0b\x65lapsed_sec\x18\x03 \x01(\x01\x32\x80\x01\n\x10PortfolioService\x12\x34\n\x0bGetSnapshot\x12\x0c.quant.Empty\x1a\x17.quant.SnapshotResponse\x12\x36\n\x0fTriggerPipeline\x12\x0c.quant.Empty\x1a\x15.quant.PipelineStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'portfolio_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SNAPSHOTRESPONSE']._serialized_start=41
  _globals['_SNAPSHOTRESPONSE']._serialized_end=182
  _globals['_PIPELINESTATUS']._serialized_start=184
  _globals['_PIPELINESTATUS']._serialized_end=255
  _globals['_PORTFOLIOSERVICE']._serialized_start=258
  _globals['_PORTFOLIOSERVICE']._serialized_end=386
# @@protoc_insertion_point(module_scope)
