# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: regime.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'regime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cregime.proto\x12\x05quant\"\x07\n\x05\x45mpty\"\x87\x01\n\x0eRegimeResponse\x12\x0f\n\x07\x63urrent\x18\x01 \x01(\t\x12\x11\n\tbull_prob\x18\x02 \x01(\x01\x12\x15\n\rsideways_prob\x18\x03 \x01(\x01\x12\x11\n\tbear_prob\x18\x04 \x01(\x01\x12\x12\n\nconfidence\x18\x05 \x01(\x01\x12\x13\n\x0b\x64\x65tected_at\x18\x06 \x01(\t2\x7f\n\rRegimeService\x12\x37\n\x10GetCurrentRegime\x12\x0c.quant.Empty\x1a\x15.quant.RegimeResponse\x12\x35\n\x0cStreamRegime\x12\x0c.quant.Empty\x1a\x15.quant.RegimeResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'regime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=23
  _globals['_EMPTY']._serialized_end=30
  _globals['_REGIMERESPONSE']._serialized_start=33
  _globals['_REGIMERESPONSE']._serialized_end=168
  _globals['_REGIMESERVICE']._serialized_start=170
  _globals['_REGIMESERVICE']._serialized_end=297
# @@protoc_insertion_point(module_scope)
