# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: signals.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'signals.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsignals.proto\x12\x05quant\"0\n\rSignalRequest\x12\x10\n\x08strategy\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\"u\n\x06Signal\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x11\n\tdirection\x18\x02 \x01(\t\x12\x10\n\x08strength\x18\x03 \x01(\x01\x12\x10\n\x08strategy\x18\x04 \x01(\t\x12\x0e\n\x06regime\x18\x05 \x01(\t\x12\x14\n\x0cgenerated_at\x18\x06 \x01(\t\",\n\nSignalList\x12\x1e\n\x07signals\x18\x01 \x03(\x0b\x32\r.quant.Signal2L\n\rSignalService\x12;\n\x10GetLatestSignals\x12\x14.quant.SignalRequest\x1a\x11.quant.SignalListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'signals_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNALREQUEST']._serialized_start=24
  _globals['_SIGNALREQUEST']._serialized_end=72
  _globals['_SIGNAL']._serialized_start=74
  _globals['_SIGNAL']._serialized_end=191
  _globals['_SIGNALLIST']._serialized_start=193
  _globals['_SIGNALLIST']._serialized_end=237
  _globals['_SIGNALSERVICE']._serialized_start=239
  _globals['_SIGNALSERVICE']._serialized_end=315
# @@protoc_insertion_point(module_scope)
