-- Migration: Trade post-mortem + news attribution + daily reports
-- Phase 2A/2B/2C tables

-- ─── swing_trade_postmortem ──────────────────────────────────
-- One row per closed position. Computed at exit + daily refresh for open positions.
CREATE TABLE IF NOT EXISTS swing_trade_postmortem (
    position_id BIGINT PRIMARY KEY REFERENCES swing_positions(position_id) ON DELETE CASCADE,
    symbol VARCHAR(10) NOT NULL,
    entry_time TIMESTAMPTZ NOT NULL,
    exit_time TIMESTAMPTZ,
    entry_price NUMERIC(12,4),
    exit_price NUMERIC(12,4),
    qty NUMERIC(12,4),

    -- Realized (denormalized)
    realized_pct DOUBLE PRECISION,
    realized_pnl DOUBLE PRECISION,
    hold_days INT,

    -- Sweeney 1997 — MFE/MAE
    mfe_pct DOUBLE PRECISION,
    mfe_date DATE,
    mae_pct DOUBLE PRECISION,
    mae_date DATE,
    capture_ratio DOUBLE PRECISION,         -- realized_pct / mfe_pct
    exit_difficulty DOUBLE PRECISION,       -- (mfe - realized) / mfe

    -- Tharp R-multiples
    initial_risk DOUBLE PRECISION,          -- entry - stop_loss
    r_multiple DOUBLE PRECISION,            -- realized_pnl / initial_risk

    -- Event study (Phase 2B)
    beta DOUBLE PRECISION,
    market_return_during_hold DOUBLE PRECISION,
    cumulative_ar DOUBLE PRECISION,
    entry_day_ar DOUBLE PRECISION,

    -- News attribution (Phase 2B)
    news_count INT DEFAULT 0,
    top_news JSONB,                         -- [{date, headline, source, relevance, sentiment, ar_1d}]
    news_explained_pct DOUBLE PRECISION,    -- fraction of P&L attributed to news vs market vs residual
    market_explained_pct DOUBLE PRECISION,
    residual_pct DOUBLE PRECISION,

    -- Exit attribution (5-Layer)
    exit_layer VARCHAR(20),
    exit_reason VARCHAR(30),

    -- Counterfactual (Phase 2D) — what other layers would have produced
    counterfactual_exits JSONB,             -- {L1_TRAIL: {pct, date}, L2_HARD: {pct, date}, ...}

    -- LLM narrative (Phase 2E)
    llm_narrative TEXT,
    llm_narrative_at TIMESTAMPTZ,
    llm_one_liner TEXT,

    computed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_open BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_postmortem_symbol ON swing_trade_postmortem(symbol);
CREATE INDEX IF NOT EXISTS idx_postmortem_exit_time ON swing_trade_postmortem(exit_time DESC);


-- ─── swing_news_attribution ──────────────────────────────────
-- Per news item × position attribution detail
CREATE TABLE IF NOT EXISTS swing_news_attribution (
    attribution_id BIGSERIAL PRIMARY KEY,
    position_id BIGINT REFERENCES swing_positions(position_id) ON DELETE CASCADE,
    event_id BIGINT,                        -- references swing_events when applicable
    symbol VARCHAR(10) NOT NULL,

    news_url TEXT,
    news_headline TEXT,
    news_source VARCHAR(50),
    news_published_at TIMESTAMPTZ,

    relevance DOUBLE PRECISION,             -- 0-100
    sentiment DOUBLE PRECISION,             -- -1 to +1
    fundamentals_focus BOOLEAN DEFAULT FALSE,
    sec_8k_item VARCHAR(20),                -- e.g. "2.02", "1.03"

    ar_0 DOUBLE PRECISION,                  -- abnormal return on news day
    ar_1 DOUBLE PRECISION,                  -- AR next day
    car_2d DOUBLE PRECISION,                -- cumulative AR [0, +1]
    attribution_dollars DOUBLE PRECISION,   -- estimated $ impact

    computed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_news_attr_position ON swing_news_attribution(position_id);
CREATE INDEX IF NOT EXISTS idx_news_attr_symbol ON swing_news_attribution(symbol);
CREATE INDEX IF NOT EXISTS idx_news_attr_published ON swing_news_attribution(news_published_at DESC);


-- ─── swing_daily_report ──────────────────────────────────
-- One row per trading day. Generated by post_market_analysis job at 06:00 KST.
CREATE TABLE IF NOT EXISTS swing_daily_report (
    report_date DATE PRIMARY KEY,

    -- Session headline
    daily_pnl DOUBLE PRECISION,
    cumulative_return DOUBLE PRECISION,
    drawdown_from_peak DOUBLE PRECISION,
    spy_return DOUBLE PRECISION,
    qqq_return DOUBLE PRECISION,
    regime VARCHAR(20),
    macro_score DOUBLE PRECISION,
    vix DOUBLE PRECISION,

    -- Positions
    closed_count INT DEFAULT 0,
    closed_pnl DOUBLE PRECISION DEFAULT 0,
    closed_position_ids BIGINT[],
    open_count INT DEFAULT 0,
    open_position_ids BIGINT[],

    -- Decision metrics (rolling 30 trades)
    rolling_30_trades INT,
    rolling_30_win_rate DOUBLE PRECISION,
    rolling_30_expectancy_pct DOUBLE PRECISION,
    rolling_30_sqn DOUBLE PRECISION,
    rolling_30_information_coefficient DOUBLE PRECISION,
    rolling_30_auc DOUBLE PRECISION,

    -- IC 개선(A): 정책 중립 신호 IC (진입 점수 ↔ forward N거래일 수익)
    rolling_signal_ic DOUBLE PRECISION,
    rolling_signal_ic_n INT,
    factor_ic_detail JSONB,                 -- {technical, sentiment, flow, quality, value, macro} Spearman IC

    -- Brinson decomposition (rough, daily)
    brinson_market DOUBLE PRECISION,
    brinson_sector DOUBLE PRECISION,
    brinson_selection DOUBLE PRECISION,
    brinson_residual DOUBLE PRECISION,

    -- Anomaly flags (Phase 2C)
    anomaly_flags JSONB,                    -- {slippage_bps, latency_ms, data_stale, ...}

    -- LLM narrative (Phase 2E)
    llm_narrative TEXT,
    llm_narrative_at TIMESTAMPTZ,

    -- Top news of the day (for held positions)
    top_news_today JSONB,

    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_daily_report_date ON swing_daily_report(report_date DESC);

-- ─── IC 개선(A): 기존 DB용 멱등 ALTER (신호 forward IC 컬럼) ──
ALTER TABLE swing_daily_report ADD COLUMN IF NOT EXISTS rolling_signal_ic   DOUBLE PRECISION;
ALTER TABLE swing_daily_report ADD COLUMN IF NOT EXISTS rolling_signal_ic_n INT;
ALTER TABLE swing_daily_report ADD COLUMN IF NOT EXISTS factor_ic_detail    JSONB;

-- ─── IC 개선(A/B/C): 신규 config 기본값 (멱등) ──
INSERT INTO swing_config (key, value, category, description) VALUES
    ('signal_ic_horizon_days',     '5',    'scoring', '신호 IC forward 수익 산출 기간(거래일)'),
    ('rsi2_exit_min_r',            '1.0',  'exit',    'RSI(2) 조기청산 최소 R배수 (이 이상 수익 시에만 rsi2 청산 허용)'),
    ('rsi2_exit_min_gain',         '0.03', 'exit',    'RSI(2) 조기청산 최소 수익률 (entry_atr 없을 때 게이팅)'),
    ('momentum_overext_enabled',   'true', 'scoring', '모멘텀 과열 페널티 활성화 (rank 상단 역U자 교정)'),
    ('momentum_overext_threshold', '0.80', 'scoring', '모멘텀 과열 페널티 시작 rank 임계값'),
    ('momentum_overext_penalty',   '0.6',  'scoring', '임계 초과분 가산 비율 (1=무감쇠, 0=상한고정)')
    ON CONFLICT (key) DO NOTHING;


-- ─── Add admin permission for new pages ──
INSERT INTO user_role_permissions (role, page_path) VALUES ('admin', '/analysis')
    ON CONFLICT DO NOTHING;
